### ISSUE TITLE
pulling resources with no credentials

### ISSUE THREAD

**Issue by tomkralidis** [transifex/transifex-client#100]
Hi: running `tx pull -a` against https://www.transifex.com/projects/p/GeoHealthCheck __without__ a `~/.transifexrc` file yields the following:

```bash
$ tx pull -a
Exception: No user credentials found for host https://www.transifex.com. Edit ~/.transifexrc and add the appropriate info in there.
```
Does `tx pull` always require credentials, even for a public project?  Is there value in supporting non-authenticated pull access?

My context is having a setup workflow for users which pulls the latest translations and then compiles them.  This also helps with Travis CI build workflow (currently our travis build [errors out](https://travis-ci.org/geopython/GeoHealthCheck/builds/86689110)).

**Comment by diegobz** [comment]
You can use [env variables](http://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings) in Travis to achieve that. You can have a `txpull.sh` file with the following content. :)

```
# Write .transifexrc file
cat > ~/.transifexrc <<EOF
[https://www.transifex.com]
hostname = https://www.transifex.com
username = ${TRANSIFEX_USERNAME}
password = ${TRANSIFEX_PASSWORD}
token = 
EOF
tx pull -a
```
