### ISSUE TITLE
Error: "txclib.utils.HttpNotFound: Not Found"

### ISSUE THREAD

**Issue by ezmiller** [transifex/transifex-client#112]
I am trying to add a new project, but am getting the following error when I run `tx push -s -t`:

```Bash
Pushing translations for resource beavy.server:
Pushing source file (var/server-messages/beavy-server.json)
Pushing 'de' translations (file: beavy/translations/de/beavy_server.json)
Pushing translations for resource beavy.web:
Pushing source file (var/react-intl-messages/beavy-core.json)
Pushing 'de' translations (file: beavy/translations/de/beavy_web.json)
Pushing translations for resource hackernews.web:
Pushing source file (var/react-intl-messages/hacker-news.web.json)
Resource does not exist.  Creating...
Traceback (most recent call last):
  File "/home/vagrant/venv/bin/tx", line 94, in main
    utils.exec_command(cmd, args[1:], path_to_tx)
  File "/home/vagrant/venv/lib/python3.4/site-packages/txclib/utils.py", line 198, in exec_command
    cmd_fn(*args,**kwargs)
  File "/home/vagrant/venv/lib/python3.4/site-packages/txclib/commands.py", line 336, in cmd_push
    no_interactive=options.no_interactive
  File "/home/vagrant/venv/lib/python3.4/site-packages/txclib/project.py", line 608, in push
    self._create_resource(resource, project_slug, fileinfo, filename)
  File "/home/vagrant/venv/lib/python3.4/site-packages/txclib/project.py", line 1221, in _create_resource
    r, charset = make_request(method, hostname, url, username, passwd, data)
  File "/home/vagrant/venv/lib/python3.4/site-packages/txclib/utils.py", line 127, in make_request
    raise HttpNotFound(data)
txclib.utils.HttpNotFound: Not Found
```

My config for the resource that is failing looks like:

```
[hackernews.web]
file_filter = beavy/translations/<lang>/hacker-news.web.json
source_file = var/react-intl-messages/hacker-news.web.json
source_lang = en
type = KEYVALUEJSON
```

I found the issue #51 (through #71), which suggests that this problem was fixed with 0.11. I'm using 0.11 already, so I'm not sure what else might be going wrong here. Thoughts?

**Comment by diegobz** [comment]
@ezmiller It looks like there is no project called `hackernews` in Transifex. We should improve that error message though.

**Comment by ezmiller** [comment]
Thanks @diegobz! That does seem to have been the problem. A better error message would be nice. Nicer still, perhaps, would be the ability to generate new projects from the client, with a special flag perhaps?

**Comment by diegobz** [comment]
@ezmiller I'm glad it worked. Creating a project may be something that would be pushing it too much, as the project creation requires more setup info than what the CLI is aware of (today). Something to keep in mind for the future though. :) Thanks!

**Comment by ezmiller** [comment]
Yeah, incidentally, the issue came up because we (beavy.xzy) needed a way
to manage resources associated with modular elements within our system.
I.e. we have the Beavy "core", and then we have "app", and "modules." We
were hoping to be able to create some sort of subdivision with the Beavy
project, perhaps "folders", so something like beavy.apps.hacker-news.web
But that wasn't possible, so for a moment we thought we'd manage resources
for these three types of entities in distinct projects. Now we are just
going with a naming convention: beavy-apps-hacker-news-web, etc etc.
