### ISSUE TITLE
Invalid SSL certificate when pulling a resource

### ISSUE THREAD

**Issue by metc** [transifex/transifex-client#113]
Hello,

I am not able to pull resources suing the following commands. I always get the same `Invalid SSL certificate` error.

```sh
$ tx --version
0.11
$ tx status
eln -> en_uslang (1 of 1)
Translation Files:
 - en_US: src/main/resources/assets/eln/lang/<lang>.lang (source)
 - _en_GB: src\main\resources\assets\eln\lang\_en_GB.lang
[...]
$ tx pull -r eln.en_uslang
Invalid SSL certificate
```

Is there any verbose mode to get a trace of the issue ? Any help is welcome.

**Comment by dimoschi** [comment]
@metc can you try `tx --traceback pull -r eln.en_uslang` and c/p the outcome. You can also find useful information in Transifex documentation, [here](http://docs.transifex.com/client/).

**Comment by metc** [comment]
Sorry, my fault. I did not see the debug section in the doc. Here is the output trace:

```sh
$ tx --debug pull -r eln.en_uslang
Path to tx is D:\git\ElectricalAge.
Config file is D:\git\ElectricalAge\.tx\config
.transifexrc file is at D:\git\ElectricalAge
.transifexrc file is at C:\Users\<username>
Operating on resources: ['eln.en_uslang']
Handling resource eln.en_uslang
Language mapping is: Flipdict({})
URL data are: {'project': 'eln', 'host': 'https://www.transifex.com', 'resource': 'en_uslang'}
Invalid SSL certificate
[Errno 2] No such file or directory
```
```sh
$ tx --traceback pull -r eln.en_uslang
Invalid SSL certificate
```
Thanks for your help

**Comment by metc** [comment]
This is the URL of the resource I'd like to pull: `https://www.transifex.com/electrical-age/eln/en_uslang/`

**Comment by metc** [comment]
The commit https://github.com/transifex/transifex-client/commit/ad33b5fe30a52474f324c55a609d660495d2a89c could fix my problem ? Should I try to compile the client from sources ?

**Comment by metc** [comment]
The issue is fixed when compiling the client from  the master branch. Would be great to release it soon ;)

**Comment by nelefth** [comment]
@metc thank you for letting us know that your issue has been resolved. Please don't hesitate to contact us at support@transifex.com in case you need any further assistance.

**Comment by metc** [comment]
@dimoschi @nelefth  Have you planned to release a new version soon ? I had to compile the from the latest sources to make it working :unamused:

Btw, I get this error when I use the client with Travis: https://travis-ci.org/Electrical-Age/ElectricalAge/builds/120698444 - Any help is welcome.

**Comment by diegobz** [comment]
@metc We have it in our TODO. Try `pip install git+git://github.com/transifex/transifex-client.git@master
` in the meanwhile.

**Comment by metc** [comment]
Thank you, I will try this.

**Comment by metc** [comment]
Hi @diegobz , thanks for your help. Unfortunately, I cannot make it working with Travis, see https://travis-ci.org/Electrical-Age/ElectricalAge/builds/121225906#L210. I am not able to find an example or any information about the issue. Any advice or suggestion ?

**Comment by diegobz** [comment]
It looks like you need at least Python 2.7.9 to get around this issue. We probably need to update our requirements to reflect it before the new release. 

@kouk, @tabac ^^

**Comment by metc** [comment]
Could you please re-open this issue until it is fixed ? Thanks

**Comment by kouk** [comment]
reopening until the release.

**Comment by metc** [comment]
Ping ;) Is someone working on it ?
I do not see any progress since February. Should I consider to use another way to sync my languages files ? Maybe the Gradle client ?

**Comment by kouk** [comment]
@metc the new release is out! So i'm closing this issue now. Let us know if you experience any other problems.

**Comment by metc** [comment]
@kouk Thanks for your message and the update.
I use the client with Travis for CI. I still get an error when installing the client: https://travis-ci.org/Electrical-Age/ElectricalAge/builds/137067005#L598

Which version of `pip` and `python` should I use ?

**Comment by kouk** [comment]
Sorry to hear that. I'll take a look tomorrow and get back to you

**Comment by kouk** [comment]
@metc I see two issues with the travis build you linked to. First you are installing the client from master (which should be OK, but not necessary anymore). Second apparently the version of pip you are using is lacking some dependencies for proper SSL requests. This can be solved I believe either by upgrading the python version you have in your travis worker (which is 2.7.3 AFAICS) or by doing `pip install 'requests[security]'`. Let me know if that fixes thigns.

**Comment by metc** [comment]
Thanks for your reply. I try both options but the build script still failed. I cannot find any good example on how to use Travis with the Transifex client.
This is the current Travis build script (errored):
 * https://github.com/Electrical-Age/ElectricalAge/blob/develop/.travis.yml
 * https://travis-ci.org/Electrical-Age/ElectricalAge/builds/138713463

I do not know how I can choose the Python version because the main project is written in Java.

**Comment by kouk** [comment]
@metc you probably have an error in your travis.yml that I'm afraid I cannot debug. As a suggestion you might try passing the `--user` flag to `pip install`. In any case here's an example of using the client with Travis: https://github.com/transifex/txci

**Comment by metc** [comment]
Yes, it is more a Travis problem. Sorry for the noise.
Everything works fine now. Thanks for your help and this new release :notes:
