### ISSUE TITLE
tx command not found in 0.12.1

### ISSUE THREAD

**Issue by patoroco** [transifex/transifex-client#122]
Hi,

I'm using Mac OS X, and after do `pip install transifex-client --upgrade` from 0.11 to 0.12.1, `tx` command disappeared.

I was looking for it in `/usr/local/bin/tx` folder, but it isn't there...

I tried to install it inside a `virtualenv` (using `pip install` too), and it created `~/.virtualenvs/virtualenv/bin/tx` as I expected, but I would like to use it at system level.

Finally I cp&paste manually from these virtualenv to `/usr/local/bin/tx` and it's running correctly, but it seems like something was damaged from 0.11 to 0.12 versions.

Reading `setup.py` history, I found https://github.com/transifex/transifex-client/commit/8f31be9888e8e82a0c0ebbfdd1ac5911f4d4e073#diff-2eeaed663bd0d25b7e608891384b7298R16 which could be related with that, but I'm not too familiar with python to be sure of that, so... any suggestion?

**Comment by kouk** [comment]
Hi @patoroco, I've tested it myself on Mac OS X El Capitan and I can't seem to reproduce the problem. Could you check and see where your `pip` binary is? E.g. `which pip`.

**Comment by patoroco** [comment]
Hi @kouk, thanks for your reply. I did `which pip` and it returned: `/usr/local/bin/pip`

As I told, this was working correctly with 0.11 version, and I didn't update pip. It's strange..

**Comment by kouk** [comment]
may I suggest you pip uninstall transifex-client and then re-install it? Also you might want to check in case you have multiple versions of the client installed by chance.

**Comment by patoroco** [comment]
I got it working copy pasting script manually, so currently I don't have a 'virgin' environment. If you didn't have this problem, maybe it's better to close the issue because no more people have this issue. What do you think @kouk ?

**Comment by kouk** [comment]
@patoroco thanks for the update. I'll keep the issue open if you don't mind, for a short while longer, in case someone else comes along who is facing the same problem.

**Comment by patoroco** [comment]
Thanks @kouk

**Comment by diegobz** [comment]
I'm closing this as it's been a while and no one else seems to have faced something similar.
