### ISSUE TITLE
Connection Pool error

### ISSUE THREAD

**Issue by laoneo** [transifex/transifex-client#126]
When I download from transifex with the client, I'm getting the following error:

> MaxRetryError: HTTPSConnectionPool(host='www.transifex.com', port=None): Max retries exceeded with url: /api/2/project/DPCalendar/resource/plg_dpcalendar_caldav-sys/translation/sl_SI/?file (Caused by <class 'socket.error'>: [Errno 111] Connection refused)

**Comment by nelefth** [comment]
@laoneo 

**#1:** Could you please share the command you type in order to download the translation file? I used tx pull -a and I was able to download all the translation files from the project you mentioned without issues.

**#2:**Could you please make sure that you use the latest version of Transifex client (0.12.1)? Use `tx --version` in order to find your current version and `pip install --upgrade transifex-client` in order to upgrade to the latest one. 

**#3:** please check how your [.transifexrc](http://docs.transifex.com/client/config/#transifexrc) and [.tx/config](http://docs.transifex.com/client/config/#txconfig) should look like. Can you share some details on how your files look like? Please make sure that the correct hostname is used in both files.

**Comment by laoneo** [comment]
Command is `tx pull -a -s -f`. I'm using the latest from master and the files are the default ones which worked since ages. So the configuration should not be an issue.

**Comment by kouk** [comment]
@laoneo could this be a transient error? Are you still having this problem?

**Comment by laoneo** [comment]
Unfortunately not. Just tried it in the last couple of days here and there and it never worked. I'm on Linux in a Vagrant Box:

````
$ uname -a
Linux  4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
````

**Comment by laoneo** [comment]
Additionally when I run the `tx pll -a -s -f` command, then my whole network looses connection to the internet. SO it looks like something with the session management is broken in the transifex client.

**Comment by kouk** [comment]
@laoneo sounds like there is a network configuration problem. I've never heard of the transifex client affecting network connectivity. What do you mean exactly by "network looses connection"? Do you mean you cannot browse websites with your browser?

**Comment by laoneo** [comment]
Is it a problem that it runs in vagrant? Are you using it in vagrant as well? It was working fine with the older release and on Ubuntu 14.04.

**Comment by kouk** [comment]
@laoneo any progress here? I know some people have run it in Vagrant, but of course it depends on what kind of configuration you use and what image etc.

**Comment by laoneo** [comment]
This question I have to ask you. I gave you my environment information. DO you need more information or how do you think this should be solved then? I can't help here much more as it is your software which is causing trouble.

**Comment by kouk** [comment]
@laoneo I'm sorry to hear that there is still this problem. Is it possible to share with us the Vagrant box that is causing the problem? Or at least the vagrant configuration? In a gist or pastebin for example.

**Comment by laoneo** [comment]
I will try to set up a fresh machine and will see if I can reproduce the issue, give me some days.

**Comment by laoneo** [comment]
Sorry for the late response, but had busy days. Now I did a complete fresh set up where I could reproduce the issue.

Host:
- vagrant init ubuntu/trusty64
- vagrant up
- vagrant ssh

VM:
- sudo apt-get install git
- sudo apt-get install python-setuptools
- git clone http://code.transifex.com/transifex-client
- cd transifex-client
- sudo python setup.py install
- create transifexrc config file
- mkdir test
- cd test
- mkdir .tx
- nano .tx/config # create a config file with 50 resources, every resource has about 50 different languages
- tx pull -a -s -f

Machine hangs after 15 fetch of resources.

**Comment by laoneo** [comment]
Could you reproduce the issue?

**Comment by paprika27** [comment]
I'm having the same issue. Why would it try to connect without a port? is that a root cause?

**Comment by paprika27** [comment]
I updated to 0.12.4 and this problem went away

**Comment by laoneo** [comment]
Since a new install from master, the problem went away. Closing it then.
