### ISSUE TITLE
force tx to use python3 even if python2 is set as default

### ISSUE THREAD

**Issue by Sopor-** [transifex/transifex-client#127]
It would be great if it was possible to force tx to use python 3 even if i have python 2 as default. Now when i run on python 2 i get this message:
```
/usr/local/lib/python2.7/dist-packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning. SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning. InsecurePlatformWarning
/usr/local/lib/python2.7/dist-packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning. InsecurePlatformWarning
```
I then compile it with python3 but i can't have python3 as default. Why can't i run python3 as default? It makes other programs fail. So maybe you could add a command line switch that use python3 instead of python or maybe you have another solution?
To change python i run `update-alternatives --config python`.

**Comment by kouk** [comment]
@Sopor this error is caused by some missing libraries. Unfortunately we cannot directly depend on them because they aren't always available for every platform. If they are available for your platform you should be able to do:
```
pip install "urllib3[secure]"
```
I believe that will make the error go away.
For more information check this [SO post](http://stackoverflow.com/questions/29099404/ssl-insecureplatform-error-when-using-requests-package).

**Comment by Sopor-** [comment]
Sorry but i get the same error. As you can read in the message the only solution is to install newer version of python "You can upgrade to a newer version of Python to solve this."

**Comment by kouk** [comment]
@Sopor could you give me the output of `pip freeze` ?

**Comment by Sopor-** [comment]
```
$ pip freeze
apt-xapian-index==0.45
certifi==2016.2.28
cffi==1.7.0
chardet==2.0.1
colorama==0.2.5
configobj==4.7.2
cryptography==1.4
dnspython==1.11.1
enum34==1.1.6
gyp==0.1
html5lib==0.999
idna==2.1
ipaddress==1.0.16
ndg-httpsclient==0.4.1
PAM==0.4.2
pyasn1==0.1.9
pycparser==2.14
pycrypto==2.6.1
pycurl==7.19.3
pyinotify==0.9.4
pyOpenSSL==16.0.0
pyserial==2.6
pysqlite==1.0.1
python-apt===0.9.3.5ubuntu2
python-dateutil==2.4.2
python-debian===0.1.21-nmu2ubuntu2
requests==2.8.1
six==1.10.0
ssh-import-id==3.21
svtplay-dl==1.2
transifex-client==0.12.1
Twisted-Core==13.2.0
urlgrabber==3.9.1
urllib3==1.16
virtualenv==1.11.4
yum-metadata-parser==1.1.4
zope.interface==4.0.5
```

**Comment by kouk** [comment]
@sopor sorry for the misunderstanding. This issue has been already resolved in the `master` branch, which however is not released to pypi. You can verify by installing transifex-client directly from github, i.e.:
`pip install -e git+https://github.com/transifex/transifex-client.git#egg=transifex-client`

**Comment by kouk** [comment]
In any case, the message you are getting is simply a warning. It doesn't block the client from working.

**Comment by Sopor-** [comment]
@kouk I'm already running master but you maybe have made some changes recently? I will pull and see if it is gone. Yes, i know it will still run but when you run a program you don't want to see warning/error messages. It should be clean :)

**Comment by Sopor-** [comment]
No warning messages anymore, nice :)
