### ISSUE TITLE
Runnging a pull on a resource returns "HTTP not found" even if it exists (but only for some resources)

### ISSUE THREAD

**Issue by eldy** [transifex/transifex-client#128]
Today, if i ran
tx --debug --traceback pull -l fr_FR -r dolibarr.interventions
everything is ok.
But if i run
tx --debug --traceback pull -l fr_FR -r dolibarr.languages
It return a HTTP not found.
Both resource "interventions" and "languages" exists since several years now. If i look on web interface, the resource "languages" is present.

This is stack trace of command that fails:

Path to tx is /home/ldestailleur/git/dolibarr.
Config file is /home/ldestailleur/git/dolibarr/.tx/config
.transifexrc file is at /home/ldestailleur
.transifexrc file is at /home/ldestailleur/git/dolibarr
Operating on resources: ['dolibarr.languages']
Handling resource dolibarr.languages
Language mapping is: Flipdict({'sw': 'sw_SW', 'sr@latin': 'sr_RS', 'uz': 'uz_UZ'})
URL data are: {'project': 'dolibarr', 'host': 'https://www.transifex.com', 'resource': 'languages'}
https://www.transifex.com/api/2/project/dolibarr/resource/languages/stats/
Not Found
Traceback (most recent call last):
  File "/usr/local/bin/tx", line 93, in main
    utils.exec_command(cmd, args[1:], path_to_tx)
  File "/usr/local/lib/python2.7/dist-packages/txclib/utils.py", line 140, in exec_command
    cmd_fn(*args,**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/txclib/commands.py", line 361, in cmd_pull
    mode=options.mode, pseudo=pseudo
  File "/usr/local/lib/python2.7/dist-packages/txclib/project.py", line 398, in pull
    stats = self._get_stats_for_resource()
  File "/usr/local/lib/python2.7/dist-packages/txclib/project.py", line 1080, in _get_stats_for_resource
    r = self.do_url_request('resource_stats')
  File "/usr/local/lib/python2.7/dist-packages/txclib/project.py", line 828, in do_url_request
    raise Exception(r.data)
Exception: Not Found

**Comment by eldy** [comment]
A change was probably introduced recently because a push on same resource now fails too with error
"This slug is reserved"
So it seems it is no more possible to use a resource called "languages". But how can i deal with existing  resource that use this name and the fact that my application absolutely need to have the file with this name ?

**Comment by eldy** [comment]
I finally renamed the resource languages into languages-not-res and change the tx/config file to match this and everything seems to work correctly now.

**Comment by dimoschi** [comment]
@eldy We took the decision to make languages reserved and so we changed the slug of every resource appending a number at the end. You could find the new slug by accessing the [project resources](https://www.transifex.com/dolibarr-association/dolibarr/content/) and click on the desired resource.

It seems very unlikely however that only this resource has not been changed, but since you have changed we cannot verify that easily.
