### ISSUE TITLE
errors should return non-zero exit code

### ISSUE THREAD

**Issue by mfournier** [transifex/transifex-client#138]
It seems the CLI returns `0` even when errors occur. Example:

```
# tx pull
Directory has not been initialzied. Did you forget to run 'tx init' first?
# echo $?
0
```

```
# tx pull
/root/.transifexrc not found.
Done.
# echo $?
0
```

Having `tx` return a non-zero code in these cases would allow users to rely on it in scripts or other unattended jobs.

Thanks !

**Comment by samuelchan22** [comment]
@mfournier We've released a new version of the client (v.0.12.5) which addresses this issue!
