### ISSUE TITLE
`tx pull` gives only "IndexError: no such group"

### ISSUE THREAD

**Issue by m-aciek** [transifex/transifex-client#139]
`tx pull` does not succeed and not very meaningful error is given – I suppose it comes from some regular expression.

My `.tx/config`:

```
[main]
host = https://www.transifex.com

[django-docs.index]
file_filter = django-docs-translations/translations/<locale>/index.po
source_lang = en

[django-docs.intro]
file_filter = django-docs-translations/translations/<locale>/intro.po
source_lang = en

[django-docs.contents]
file_filter = django-docs-translations/translations/<locale>/contents.po
source_lang = en

[django-docs.faq]
file_filter = django-docs-translations/translations/<locale>/faq.po
source_lang = en

[django-docs.howto]
file_filter = django-docs-translations/translations/<locale>/howto.po
source_lang = en

[django-docs.internals]
file_filter = django-docs-translations/translations/<locale>/internals.po
source_lang = en

[django-docs.misc]
file_filter = django-docs-translations/translations/<locale>/misc.po
source_lang = en

[django-docs.reference]
file_filter = django-docs-translations/translations/<locale>/reference.po
source_lang = en

[django-docs.releases]
file_filter = django-docs-translations/translations/<locale>/releases.po
source_lang = en

[django-docs.topics]
file_filter = django-docs-translations/translations/<locale>/topics.po
source_lang = en
```

**Comment by nelefth** [comment]
@m-aciek One suggestion I could provide you with is to replace "<locale>" with "<lang>" (destination folder name) in order all the translation files of the above resources to be successfully stored. 
Also, could you please make sure that you have installed the latest version of Transifex Client (0.12.2)?

**Comment by m-aciek** [comment]
Could you elaborate what exactly I should replace?
I have latest version of TC installed.
Other thing is that bug occures quite randomly, I managed once to fetch the files, but invoking same command second time would end with `IndexError: no such group` again.

**Comment by nelefth** [comment]
@m-aciek sorry. I just realized that the text inside quotes was removed after submitting the comment. 

Could you please replace "locale" with "lang" in the path that you have defined in your .tx/config file and let me know if the issue still persists?

Please let me know how it goes.

**Comment by m-aciek** [comment]
Unfortunately no change after changing the paths.
