### ISSUE TITLE
Wrong URL format in http://docs.transifex.com/client/set/#auto-remote-setup

### ISSUE THREAD

**Issue by JulienPalard** [transifex/transifex-client#140]
I'm trying to setup tx client for the french translation of the python documentation, and I'm hitting some badly documented sections, I'll try to document my failures so you can enhance your documentation.

In the `auto-remote-setup` documentation, we're told to give URI with the `https://www.transifex.com/projects/p/<project_slug>/` syntax, but I suspect you changed URI format without updating your documentation, as URI looks like `https://www.transifex.com/python-doc/`.

Blindly following the doc won't work:

```
$ tx set --auto-remote https://www.transifex.com/projects/p/python-doc/
Auto configuring local project from remote URL...
Getting details for project python-doc
txclib.exceptions.HttpNotFound: Not Found
```

**Comment by JulienPalard** [comment]
Oh, also it won't work with the right URI :(

```
$ tx set --auto-remote https://www.transifex.com/python-doc/
Auto configuring local project from remote URL...
Exception: tx: Malformed url given. Please refer to our docs: http://bit.ly/txcconfig
```

**Comment by diegobz** [comment]
@JulienPalard You are using the organization slug, rather than the project slug. I see this is a bit confusing.

Please try `tx set --auto-remote https://www.transifex.com/projects/p/python-27/`

`python-27` is actually a project slug under the `python-doc` organization.

**Comment by JulienPalard** [comment]
@diegobz OK I tried https://www.transifex.com/python-doc/python-35/ and it works. But the doc should be updated, we have no way to find the `/projects/` URI from the interface. Also the documentation should desambiguate between organization / project / resource for newcomers.

**Comment by diegobz** [comment]
Docs got updated with the new URL structure.

http://docs.transifex.com/client/set/

Thanks.
