### ISSUE TITLE
How to specify destination language?

### ISSUE THREAD

**Issue by JulienPalard** [transifex/transifex-client#143]
According to `http://docs.transifex.com/client/config/` `<lang>` is a tag of the `file_filter`, why? I'm translating from english to french, so my git repository only hosts `english to french` `.po` files, which looks right for me, but the `fr` string is nowhere in my file hierarchy. I did not find anything in the documentation to specify a `translated` language.

Yet a `source_lang` is specified for each and every "resource" in the config file (why!?) is that 464 times the same useless line? That's a bit unreadable / unmaintainable for my point of view.

**Comment by diegobz** [comment]
Usually the repositories store translations to multiple languages and this is when `<lang>` and the `file_filter` option come handy. In your use case, I think you just need to use `trans.fr = path/to/translated.po` option under each resource setting.

You can point 2 different resources to 2 different projects in the same config file, in that case the source language can be different. In the other hand, in general I think we could eventually have a default source language setting in the beginning of the file, but that's a subject for discussing in another ticket.

Closing as this is a general question.
