### ISSUE TITLE
Pullling a resource that doesn't exist in Transifex throws a generic "HttpNotFound: Not Found" error

### ISSUE THREAD

**Issue by diegobz** [transifex/transifex-client#146]
The error message should be improved describing at least what resource is involved and eventually ways to fix it, like:

You are trying to download translations for a file (<proj>.<res>) that doesn't exist in Transifex yet. You probably want to push your source file first with `tx push -r <proj>.<res> -s` so translation files can be downloaded from the system afterwards.

**Comment by samuelchan22** [comment]
Addressed in the PR (#168) above.
