### ISSUE TITLE
Show python version and architecture when running tx --version

### ISSUE THREAD

**Issue by Sopor-** [transifex/transifex-client#147]
When i run tx --version the only thing i see is the version of TX. It would be great if it could show even python version and architecture of the tx.exe file so i know which file i'm using. I always change name to tx.exe and then i forget what version i was using :(
```
tx --version
0.12.2, py 3.5, x64
```

**Comment by samuelchan22** [comment]
@Sopor- We've released a new version of the client (v.0.12.5) which now includes the details you've requested :)

**Comment by Sopor-** [comment]
Unfortunately i can't update until this issue is fixed https://github.com/transifex/transifex-client/issues/148
