### ISSUE TITLE
can't pull even if i'm using --force

### ISSUE THREAD

**Issue by Sopor** [transifex/transifex-client#148]
I'm having problem to pull from transifex. It seems to not downloading from transifex. I'm running a script every day that will download changed language but now suddenly it won't work any more. I have updated everything incl TX to 0.12.2 but it still won't work. I then was going to try the option -f to force it to download but it still won't download anything.
`$ tx -r /the/path/to/the/resource pull -a --mode=reviewed`
and the output is an empty line
As i already mentioned, it has worked for years.
I did a test on Windows and it seems that 0.12.1 works but not 0.12.2 and i did try them all tx.py27.exe, tx.py27.x64.exe, tx.py35.exe and tx.py35.x64.exe. I only see an empty line (the same as in Ubuntu).
When i run `tx pull -a --mode=reviewed` (tx is the old version 0.12.1) it will download the files. Even the -f will force it to download all files even if none of them have been changed.
```
 -> ro_RO: airdcpp.en_examplexml\ro-RO.xml
 -> no_NO: airdcpp.en_examplexml\no-NO.xml
 -> fr_FR: airdcpp.en_examplexml\fr-FR.xml
 -> pt_BR: airdcpp.en_examplexml\pt-BR.xml
 -> fi_FI: airdcpp.en_examplexml\fi-FI.xml
 -> da_DK: airdcpp.en_examplexml\da-DK.xml
 -> it_IT: airdcpp.en_examplexml\it-IT.xml
 -> sv_SE: airdcpp.en_examplexml\sv-SE.xml
 -> hu_HU: airdcpp.en_examplexml\hu-HU.xml
 -> nl_NL: airdcpp.en_examplexml\nl-NL.xml
 -> de_DE: airdcpp.en_examplexml\de-DE.xml
 -> pl_PL: airdcpp.en_examplexml\pl-PL.xml
 -> ru_RU: airdcpp.en_examplexml\ru-RU.xml
 -> es_ES: airdcpp.en_examplexml\es-ES.xml
Done.
```

**Comment by nelefth** [comment]
@Sopor- I tried to reproduce the issue you reported and I found that the only language files that are downloaded [empty](http://www.screencast.com/t/25eoYoJ09ho) are the following ones:

el_GR.xml
hu.xml
uk_UA.xml
vi.xml

After checking the translations in Transifex, I confirmed that no strings have been reviewed for the above language codes. 
 
So, what I experienced is the expected behavior. 

Also, I tried to pull again the translation files that I downloaded previously using the -f option and all the files were downloaded as expected. 

Not sure which part of your scenario I am missing, though. 

Could you please share your .tx/config file and the output you get after submitting the tx pull command line? 
In your comment, you mentioned: " try the option -f to force it to download but it still won't download anything.". Could you please share the output of this command line as well in order to have a better understanding of this issue?

This is how it works for me:

http://screencast.com/t/EjMAJ23K

**Comment by Sopor-** [comment]
As i wrote above i get only an empty line after running the TX command, not an empty language files. In the config file i have `minimum_perc = 40`.
This is what happen in Windows when i run version 0.12.2:
```
D:\transifex>tx.py27.x64 pull -a -f --mode=reviewed

D:\transifex>
```
And this if i run 0.12.1:
```
D:\transifex>tx pull -a -f --mode=reviewed
Pulling translations for resource airdcpp.en_examplexml (source: None)
 -> ro_RO: airdcpp.en_examplexml\ro-RO.xml
 -> no_NO: airdcpp.en_examplexml\no-NO.xml
 -> fr_FR: airdcpp.en_examplexml\fr-FR.xml
 -> pt_BR: airdcpp.en_examplexml\pt-BR.xml
 -> fi_FI: airdcpp.en_examplexml\fi-FI.xml
 -> da_DK: airdcpp.en_examplexml\da-DK.xml
 -> it_IT: airdcpp.en_examplexml\it-IT.xml
 -> sv_SE: airdcpp.en_examplexml\sv-SE.xml
 -> hu_HU: airdcpp.en_examplexml\hu-HU.xml
 -> nl_NL: airdcpp.en_examplexml\nl-NL.xml
 -> de_DE: airdcpp.en_examplexml\de-DE.xml
 -> pl_PL: airdcpp.en_examplexml\pl-PL.xml
 -> ru_RU: airdcpp.en_examplexml\ru-RU.xml
 -> es_ES: airdcpp.en_examplexml\es-ES.xml
Done.

D:\transifex>
```

**Comment by Sopor-** [comment]
Still no reply on this one?

**Comment by mmfoscarpeerio** [comment]
Having the same issue as well, any ideas?

init command creates the .tx folder and credentials are also in place for the .transifexrc file

**Comment by Sopor-** [comment]
@mmfoscarpeerio yes, it is strange that i haven't got any response. I can't update the languages from my Linux as it is now. I need to do it manually in Windows and then move the files to my Linux.

**Comment by mmfoscarpeerio** [comment]
After comparing the .config file in a UNIX env I found that the init command might have a bug. It's just generating the following:

[main]
host = https://www.transifex.com

It's missing the project config piece, example:

[project_name]
file_filter = <lang>.json
source_file = source.json
source_lang = en
type = JSON

Right after you add this, the push should work.

Let me know if someone else can repro this.

**Comment by Sopor-** [comment]
It seems that if i go back to commit https://github.com/transifex/transifex-client/commit/b267133c97dcc863598c02411b3ff5a7555fc3f2 it work again and if i try this commit it won't work https://github.com/transifex/transifex-client/commit/d25c3dde9553edf31f374ebb695935e4939f8d69. Somewhere between these two it fails.

**Comment by Sopor** [comment]
I was testing 0.13.6 and it seems to work now, but i do get this warning message.
`tx WARNING:  -> sv_SE: airdcpp.en_examplexml\sv-SE.xml`

Someone that knows why?
