### ISSUE TITLE
Trying to push without being maintainer only prints "Exception"

### ISSUE THREAD

**Issue by fdietze** [transifex/transifex-client#150]
```
Pushing translations for resource xxxxxx.general:
Pushing source file (.../template.pot)
Resource does not exist.  Creating...
Exception
```

A more descriptive error message would be useful to see what's wrong.

**Comment by SofiaMargariti** [comment]
This is fixed. Now the endpoint returns a descriptive message: `Exception: Only maintainers are allowed to update the source file.`
