### ISSUE TITLE
using tx behind an authenticated proxy

### ISSUE THREAD

**Issue by ebelo** [transifex/transifex-client#166]
Since https://github.com/transifex/transifex-client/pull/130 it is possible to use tx behing a proxy. But there is no way yet to get it work behind an authenticated proxy with Basic auth and username/password.

You can only submit host and port: https://docs.transifex.com/client/introduction#help

Thank you very much for any help or new feature on this issue.

**Comment by sbrunner** [comment]
Prototype: https://github.com/transifex/transifex-client/compare/master...sbrunner:authenticated-proxy

**Comment by SofiaMargariti** [comment]
Fixed here https://github.com/transifex/transifex-client/pull/170
