### ISSUE TITLE
lang_map configuration confusion

### ISSUE THREAD

**Issue by hualet** [transifex/transifex-client#174]
Hi, I don't know where to ask questions or discuss things like that, so I have to open a issue here.

My problem is that es_419 is not a valid locale name in Qt, so I need map the locale to es_ar or other es_* locales. My configuration is like:

> [main]
> host = https://www.transifex.com
> minimum_perc = 80
> mode = developer
> lang_map = es_419: es_ar
> 
> [deepin-desktop-environment.dde-control-center]
> file_filter = translations/dde-control-center_<lang>.ts
> source_file = translations/dde-control-center.ts
> source_lang = en
> type = QT

when I execute "tx pull", it gives me KeyError"es_ar"; But if I flip es_419 with es_ar, it runs without any error and creates no translations/es_ar.ts file either. 

Please tell me how can I do what I want, thanks.

**Comment by horus68** [comment]
to test start with `minimum_perc = 0` else you only get translations if 80% done
the lang_map model is `Transifex language code : Local code to be saved`

**Comment by hualet** [comment]
@horus68 Thanks, I tried the configuration within an empty directory and it works. So it seems that I just need to remove all the .ts files that already exist in the project directory. Sorry for the bother;

**Comment by hualet** [comment]
@horus68 Any plan to support one-to-many mapping?
