### ISSUE TITLE
Incorrect Apple .strings file documentation

### ISSUE THREAD

**Issue by sterlingwes** [transifex/transifex-client#178]
Not sure if this is the right place, but [your documentation](https://docs.transifex.com/formats/apple-strings) lists the wrong i18n type of `STRING` for .strings files in the client config. Received the following error referring to the docs:

```
$ tx push -s
Pushing source file (ios/Project/Base.lproj/Localizable.strings)
Resource does not exist.  Creating...
Exception: Format 'STRING' not found
```

The working type is `STRINGS`.

**Comment by samuelchan22** [comment]
Good catch, thanks for letting us know. We've updated the documentation so it now says `STRINGS`.
