### ISSUE TITLE
Version 0.12.5 of 32bit execs causes plenty of positives on VirusTotal

### ISSUE THREAD

**Issue by AdmiringWorm** [transifex/transifex-client#193]
Is there something wrong with the 32bit executable of the software?
Both the one depending on Python 2.7 and Python 3.5 causes plenty of positives on virus total.
See the following for the one depending on 2.7: https://www.virustotal.com/en/file/4392943605152e6052fcc48789b61ae7bab385d1f3a87483c8bcacfd8cd511f5/analysis/1509736911/
and the following on the one depending on 3.5:
https://www.virustotal.com/en/file/39365030dad0397af2a112d2a1e6764b5cb875c22e68efd677d6b75ef7239847/analysis/

The 64bit versions seems to be okay with only 1 positive (which is highly likely to be a false positive).

**Comment by samuelchan22** [comment]
@AdmiringWorm Thanks for bringing this up, we'll take a look and get back to you.

**Comment by AdmiringWorm** [comment]
@samuelchan22 Any update on this one?
I just ran new scans on virustotal (new links below), and the result is more or less the same.
- py27: https://www.virustotal.com/en/file/4392943605152e6052fcc48789b61ae7bab385d1f3a87483c8bcacfd8cd511f5/analysis/1510369107/
- py35: https://www.virustotal.com/en/file/39365030dad0397af2a112d2a1e6764b5cb875c22e68efd677d6b75ef7239847/analysis/1510369218/

**Comment by samuelchan22** [comment]
@adamzr We think these might be false positives. We recreated two new versions of the .exe, both containing the changes included in the v0.12.5 release. The only difference between the two versions was that one had the old version number of the client (0.12.4) and the other had the new version number (0.12.5). The one with the newer version number returned 13 warnings on Virus Total vs. 5 for the one with the older version number. For the time being, there's not much more we can do. If you have any further concerns, feel free to take a look at our code as it's Open Source.

**Comment by diegobz** [comment]
Closing this as no extra action needs to be taken.
