### ISSUE TITLE
Provide correct exit status

### ISSUE THREAD

**Issue by jprudent** [transifex/transifex-client#199]
When scripting, it's useful to have correct exit status.

```bash
$ tx --version
0.12.4

$ tx pull -a -s
Directory has not been initialzied. Did you forget to run 'tx init' first?

$ echo $?
0
```
In that case exit status should be != 0

**Comment by samuelchan22** [comment]
This has been fixed in the latest release. 

https://github.com/transifex/transifex-client/releases
