### ISSUE TITLE
support Python 3.6

### ISSUE THREAD

**Issue by eighthave** [transifex/transifex-client#208]
The upcoming releases of Ubuntu and Debian will not offer Python 3.5, and Python 2.7 is End-Of-Life quite soon.   Please support the current version of Python, 3.6.  I package transifex-client for both Debian and Ubuntu, and can't update it there until it supports Python 3.6.

* the upcoming Ubuntu/bionic LTS release currently uses 3.6.3: https://packages.ubuntu.com/bionic/python3
* the upcoming Debian/buster release currently uses 3.6.4: https://packages.debian.org/buster/python3

**Comment by eighthave** [comment]
I forgot to add, the deadline for getting things into the upcoming Ubuntu LTS release is basically the ned of January.

**Comment by cfletcher** [comment]
@eighthave does the client not support 3.6? I'm looking at the project page and it says:

> Download and install Python.
> At this step choose right version of python: 2 or 3 and x86 or x86-64 instruction set.

**Comment by eighthave** [comment]
It does not, according to the "Requires Python" listing at the bottom of
here:
https://pypi.python.org/pypi/transifex-client

Requires Python: >=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,<3.6

I haven't tested it...

**Comment by nelefth** [comment]
@eighthave a new TX client release is available [here](https://github.com/transifex/transifex-client/releases/tag/0.13.1).
