### ISSUE TITLE
Specified resource does not exist

### ISSUE THREAD

**Issue by joaomilho** [transifex/transifex-client#210]
So I've tried:

```sh
tx delete 'my-resource-slug'
tx delete 'my-resource-slug' --force
tx delete 'my-project-slug.my-resource-slug'
tx delete 'my-project-slug.my-resource-slug' --force
```

Also tried passing language, using capital letters, etc... And in all cases I've got:

```
tx ERROR: Specified resource 'my-project-slug.my-resource-slug' does not exist.
```

Any ideas?

**Comment by nelefth** [comment]
@joaomilho in order to successfully delete the desired resource, you need to use the -r option as it is described in our documentation guide [here](https://docs.transifex.com/client/delete).

i.e.
tx delete -r project_slug.resource_slug --f

Please let me know if that works for you.
