### ISSUE TITLE
pip install 0.13.0 issues

### ISSUE THREAD

**Issue by davidejones** [transifex/transifex-client#215]
pypi lists version 0.13.0 available but when i tried to install it i get the following error. 

```
Collecting transifex-client==0.13.0

  Could not find a version that satisfies the requirement transifex-client==0.13.0 (from versions: 0.1, 0.2, 0.2.1, 0.3, 0.4, 0.4.1, 0.5, 0.5.1, 0.5.2, 0.6, 0.6.1, 0.7, 0.7.2, 0.7.3, 0.8, 0.9, 0.9.1, 0.10, 0.11b0, 0.11b3, 0.11, 0.11.1b0, 0.12b0, 0.12.1, 0.12.2, 0.12.3, 0.12.4, 0.12.5)
No matching distribution found for transifex-client==0.13.0
```

**Comment by davidejones** [comment]
Ah I'm on python 3.6.1 which I'm assuming is the issue

`Requires Python: >=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,<3.6`

Is there any ETA on getting the support for 3.6 in? i see there is an issue and pr around it

**Comment by nelefth** [comment]
@davidejones I assume that you are referring to the issue [here](https://github.com/transifex/transifex-client/pull/213). Am I right?

Please note that we are already aware of this and we are planning to support this soon. Probably, this will be available by the end of February.

**Comment by davidejones** [comment]
OK thanks for the info it's much appreciated.

**Comment by nelefth** [comment]
@davidejones the new TX client release is available [here](https://github.com/transifex/transifex-client/releases/tag/0.13.1)
