### ISSUE TITLE
tx push -t followed by tx pull restore old translations

### ISSUE THREAD

**Issue by JulienPalard** [transifex/transifex-client#222]
On https://github.com/python/python-docs-fr/ we're using something like ``tx pull`` followed by a git merge followed by ``tx push -t``. It looks like it works, but when we're running ``tx pull`` again, we're receiving our old translations, not the result of the merge.

Our config is here: https://github.com/python/python-docs-fr/blob/3.6/.tx/config

**Comment by JulienPalard** [comment]
@nelefth Resource, strings, and language are here: https://github.com/python/python-docs-fr/.

**Comment by JulienPalard** [comment]
Email sent.

**Comment by lauterry** [comment]
Hi

I've got the same issue.

Have you been able to find a solution ?

If so, can you share it please ?

Best regards

**Comment by nelefth** [comment]
@lauterry ,
Can you please share more information about the workflow you use in order to properly assist you?

When you initially pull the translations from Transifex, what do you do next? Is there any new source content that needs to be pushed to Transifex? Can you please confirm that for the new translations, the corresponding source entries are already hosted at Transifex?

**Comment by JulienPalard** [comment]
@lauterry I stopped using transifex, I now simply use git (and github) instead (https://github.com/python/python-docs-fr).

**Comment by lauterry** [comment]
Hi @nelefth 

When I initially pull the translations from Transifex, I retrieve some translations that have been deleted. Those translations are not visible on Transifex so why do I manage to retrieve them ?

I confirm that the source entries of the new translations are already hosted on Transifex.

Best regards

**Comment by nelefth** [comment]
@lauterry thank you for your response. Can you please send an email at support@transifex.com with more details like the project and resource and highlight some of the entries that shouldn't be retrieved so that we can take a better look at it and properly assist you?

**Comment by lauterry** [comment]
Hi @nelefth 

It is working properly.

Sorry for the noise. 

Best regards

**Comment by nelefth** [comment]
Great @lauterry.
I am glad your issue has been resolved! 
Let us know if you need any further assistance :)
