### ISSUE TITLE
Be able to skip prompt when pulling to avoid CI blocking (> v0.12.5)

### ISSUE THREAD

**Issue by CPatchane** [transifex/transifex-client#225]
Hello,

I am Cedric, a developer from the Cozy Cloud front team. 
We use `transifex-client` via Travis to pull automatically all our applications locales during the CI using a Transifex token. And the last releases of the client added a new prompt when the authentication failed. 
When the token is provided, all work correctly.
My issue is when we want to build a project not configured yet with transifex or when we have pull requests from forks (Travis doesn't provide the encrypted token when it's from forks). In these cases the authentication failed because the token is missing. We used to have `tx pull -a || true` before to not breaking the build, but now the new prompt is clearly blocking the process and breaks the build after a timeout ([example](https://travis-ci.org/gcoter/cozy-music/builds/364055867#L746)).

Is it possible to have an option to skip this prompt and just log the failure error messages instead?
For now, the only one solution we have is to freeze our CI transifex-client to the 0.12.5 version :/

**Comment by diegobz** [comment]
Thanks for the input on this. We will take a look. Most likely we will introduce a `--no-interactive` flag as we have for the `tx push` command.

**Comment by CPatchane** [comment]
@kouk it seems to no block anymore, but I got a weird error returning a kind of an HTML page I don't know if it's related. See here https://travis-ci.org/CPatchane/cozy-music/jobs/365082992#L733

**Comment by Diontsoumas** [comment]
@CPatchane on 0.13.3 we have added a `--no-interactive` flag in the `tx pull` command, this will properly skip the user input and fail silently if the TX_TOKEN environment variable has not been set (the TX_TOKEN option also appears in 0.3.13).

**Comment by CPatchane** [comment]
Great! Thanks a lot @Diontsoumas 🎉

**Comment by brandones** [comment]
> fail silently

Could you make it fail _not_ silently, so that devs can figure out what's happened without having to find this specific GitHub Issue?
