### ISSUE TITLE
tx pull issues "WARNING:  -> fr: fr.po" but no details on what it's actually warning about

### ISSUE THREAD

**Issue by akien-mga** [transifex/transifex-client#237]
Running `tx pull -l fr -f` (force needed as described in #233), I get this output:
```
$ tx pull -l fr -f
tx INFO: Pulling translations for resource mageia.drakx_share (source: libDrakX.pot)
tx WARNING:  -> fr: fr.po
tx INFO: Done.
```

With debug:
```
$ tx -d pull -l fr -f
<snip>
tx DEBUG: Adding to new translations: set()
tx DEBUG: Pulling languages for: {'fr'}
tx INFO: Pulling translations for resource mageia.drakx_share (source: libDrakX.pot)
tx DEBUG: Using file fr.po
tx DEBUG: Downloading translation due to -f
tx WARNING:  -> fr: fr.po
tx INFO: Done.
```

This `WARNING:  -> fr: fr.po` is confusing, especially since it's not giving any details on what it's warning about. Is it meant to be an `INFO` level message?

It seems to be a recent change as I see this behaviour in 0.13.4 but it was different in 0.12.4:
```
Adding to new translations: set()
Pulling languages for: {'fr'}
Pulling translations for resource mageia.drakx_share (source: libDrakX.pot)
Using file fr.po
Downloading translation due to -f
 -> fr: fr.po
Done.
```

Apart from the `tx LEVEL:` the messages are the same, so I think the line explicating the remap is just wrongly set to `WARNING`.

**Comment by Diontsoumas** [comment]
Fixed by https://github.com/transifex/transifex-client/pull/251, thanks for your contribution!
