### ISSUE TITLE
--version information written to stderr not stdout

### ISSUE THREAD

**Issue by dhensby** [transifex/transifex-client#239]
Version affected: v0.13.4 (may affect others, this is what I've tested)

Problem: When running `tx --version` the output from the command is written to the stderr.

Expected behaviour: Output from `tx --version` should be written to the stdout.

Steps to replicate:

```sh
$ tx --version > test.txt
0.13.4, py 2.7, x86_64
$ cat test.txt
```
```sh
$ tx --version 2> test.txt
$ cat test.txt
0.13.4, py 2.7, x86_64
```

When tooling wants to inspect the version of software installed it expects to be able to read from the stdout what the output is. As the output from `tx --version` is not error output it should not be written to the stderr.

**Comment by dhensby** [comment]
Having taken a look through the code (though note I'm not experienced with python and/or argparse library) it looks as though this may be a bug with `'version'` `action` (https://docs.python.org/2/library/argparse.html#action).

Though this doesn't entirely explain the regression between 0.12 and 0.13.

What I have noticed is that in v0.12 the parser was created like this:

```py
parser = OptionParser(
    usage=usage, version=txclib.__version__, description=description
)
```

It's now created like this:

```py
parser = ArgumentParser(
    description=description, add_help=False
)
# parser.disable_interspersed_args()
parser.add_argument('--version', action='version', version=version)
```

**Comment by dhensby** [comment]
OK - so this is a bug in python (fixed in 3.4 - https://github.com/python/cpython/commit/cdac5516750e3b80b846e0e156e496dd92be9b56)

They discussed the issue here: https://bugs.python.org/issue18920 and said it wasn't worth fixing in 2.x

**Comment by rigaspapas** [comment]
Thanks for the information. Closing this, as there is nothing we can do.

**Comment by dhensby** [comment]
> there is nothing we can do.

well, that's not strictly true; instead of using the built in `action=version` a version method could be written that correctly outputs to the stdout.

I'd be happy to look into it if I can find the time and it wouldn't be rejected out of hand. This is quite a feature regression for those that rely on verifying versions of installed software
