### ISSUE TITLE
"Resource ourorgname.labels-resx doesn't exist on the server"

### ISSUE THREAD

**Issue by johnknoop** [transifex/transifex-client#240]
Hi!

I've just initialized the cli according to the guide, but when I run `tx pull -a` I get this error message:

"Resource ourorgname.labels-resx doesn't exist on the server"

Any idea what I might have done wrong?

**Comment by johnknoop** [comment]
Here's how the initialization procedure looked:

![tx](https://user-images.githubusercontent.com/3394270/46732847-e8ebf400-cc8e-11e8-8f0c-0c29668760a8.gif)

**Comment by nelefth** [comment]
@johnknoop it seems that the slug of your resource in Transifex is no longer "labels-resx".  I can see the following slugs instead:
-- BreezeProduction-Labels-resx
-- BreezeLibrary-Labels-resx

Could you please check this out and properly update your configuration file? Please let me know how it goes

**Comment by johnknoop** [comment]
Hi!

Never mind, I was able to see that some settings were overwritten when I initialized it. Was able to solve it!

Thanks
