### ISSUE TITLE
0.13.5 Installation Failed on Python 3.4

### ISSUE THREAD

**Issue by agladboy** [transifex/transifex-client#249]
As topic!

**Comment by Diontsoumas** [comment]
Python 3.4 wasn't supported as of recently, and the PR that adds support for it hasn't been released yet (but will very soon, probably this week). Under which operating system did it fail to be installed?

**Comment by agladboy** [comment]
@agladboy Thanks for confirmation and looking forward to seeing it.

I installed against Mac OS Mojave. Python package 3.4.4 downloaded from Python website.
