### ISSUE TITLE
Asking for help to solve the dependency conflict issues of the transifex-client's downstream projects

### ISSUE THREAD

**Issue by NeolithEra** [transifex/transifex-client#271]
Hi, your downstream project **_money-to-prisoners-common_** suffered from a similar dependency conflict issue caused by the tight version constraint of package **_six_** set by **_transifex-client_**.

As shown in the following link [#issue 377](https://github.com/ministryofjustice/money-to-prisoners-common/issues/377).

Could you please loosen the version constraint of **_six_**, to remove this dependency hell?

 @diegobz  Thanks for your help!

**Comment by diegobz** [comment]
Working on it. #273

**Comment by diegobz** [comment]
Version `0.13.7` is out and includes #273.
