### ISSUE TITLE
Asking for help to solve the dependency conflict issues of the transifex-client's downstream projects

### ISSUE THREAD

**Issue by NeolithEra** [transifex/transifex-client#272]
Hi, a similar issue as #271 ,  your downstream project money-to-prisoners-common suffered from a similar dependency conflict issue caused by the tight version constraint of package _**urllib3**_ set by **_transifex-client_**.

As shown in the following link [#issue 378](https://github.com/ministryofjustice/money-to-prisoners-common/issues/378).

Could you please loosen the version constraint of  _**urllib3**_, to remove this dependency hell?

Thanks for your help!

**Comment by diegobz** [comment]
Working on it. #273

**Comment by m-aciek** [comment]
Same is for installation with `requests` package, there is a conflict on `urllib3` versions. Please release master 🙏

**Comment by diegobz** [comment]
Version `0.13.7` is out and includes #273.
