### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by m-aciek** [transifex/transifex-client#277]
Could you add Python 3.8 support? On Python 3.8 pip doesn't see transifex-client > 0.12.5.

**Comment by m-aciek** [comment]
It's on master: https://github.com/transifex/transifex-client/commit/471255097ef3a74915536372e834bbae3ef25177. Please do the release then 🙏

**Comment by nelefth** [comment]
@m-aciek ,

We will proceed accordingly and release it soon!
