### ISSUE TITLE
Can't seem to push translations

### ISSUE THREAD

**Issue by littleguy77** [transifex/transifex-client#29]
Transifex has been working great for us the last several months.  I'm using the command-line tool with cygwin and have had no difficulty pulling translations and pushing the source.  However, I can't seem to push translations with the command-line tool.  It appears as though tx is not finding the translation files in the local filesystem.  Here's what happens:

```
$ tx push -t
Pushing translations for resource mupen64plus-ae.menu-strings:
Pushing translations for resource mupen64plus-ae.market-listing:
Done.
```

Using the `-f` flag doesn't change the result.  By comparison, here's the output from pull:

```
$ tx pull -a
New translations found for the following languages: ru,fr, pt, hr, ca, de, tr, it, es, gl, ja, pl
Pulling new translations for resource mupen64plus-ae.menu-strings (source: ./res/values/strings.xml)
 -> ru: res/values-ru/strings.xml
 -> fr: res/vaules-fr/strings.xml
[etc.... same for the other resources]
Done.
```

Although curiously, it always says "New translations found" and pulls everything, even when nothing has actually changed.  Perhaps related to the same issue.  And finally here's my config file:

```
[main]
host = https://www.transifex.com

[mupen64plus-ae.menu-strings]
file_filter = ./res/values-<lang>/strings.xml
source_file = ./res/values/strings.xml
source_lang = en
type = ANDROID
minimum_perc = 80

[mupen64plus-ae.market-listing]
file_filter = ./doc/publish/listing-<lang>.txt
source_file = ./doc/publish/listing.txt
source_lang = en
type = TXT
minimum_perc = 80
```

**Comment by bittner** [comment]
Is this worth a bug report, or a pull request, maybe? If you think, not being allowed to use `./` as a prefix is counter-intuitive this should probably be fixed.
