### ISSUE TITLE
Install from source not installing the latest version in Python 3.9

### ISSUE THREAD

**Issue by bodazhao** [transifex/transifex-client#311]
When I did

```sh
git clone https://github.com/transifex/transifex-client.git
cd transifex-client
python setup.py install
```

The installed version is `0.12.5`?

```sh
tx --version
# 0.12.5, py 3.9, x86_64

which tx
/Users/boda/.pyenv/shims/tx
```

macOS Catalina (10.15.7), Python 3.9 with `pyenv`

===

But if I switch to Python 3.8.6

```sh
pyenv global 3.8.6

python setup.py install
```

it works and installs the latest version

```sh
tx --version
# 0.14.2, py 3.8, x86_64
```

**Comment by pankav** [comment]
Hello,

I would like to follow up on our last email, and offer you an alternative solution to download our new Tx Client created with the Go Language.
More information about this you can find [here](https://docs.transifex.com/cli-client-in-go/introduction-to-the-client).

Hope you find this helpful.

Kind regards,
Panagiotis

**Comment by bodazhao** [comment]
Thanks, will give the new CLI a try and raise any further issues separately
