### ISSUE TITLE
AndroidFileFormat: line ending (termination) differs between template & translation > \n instead of  \r\n on windows systems

### ISSUE THREAD

**Issue by chefkoch** [transifex/transifex-client#40]
This is a sequel to https://github.com/transifex/transifex/issues/123 , but unfortunetely I am not able to post a comment to the issue there and the issue itself is also more related to the transifex-client than transifex itself.

For introduction please read https://github.com/transifex/transifex/issues/123

This is still an issue. We are working around it by applying a "fix" script to the language files after pulling the translations, nevertheless it would simplify the transifex preparation process for new plugin repositories created by our community plugin developers and also simplify the build scripts of the existing repositories.

\r\n should be used by default on windows files systems instead of \n only or maybe have it available as a commandline switch.

**Comment by diegobz** [comment]
Closing this for now, as no further action needs to be taken, apparently.
