### ISSUE TITLE
Pull functionality crashing when server has no resource created

### ISSUE THREAD

**Issue by Legoless** [transifex/transifex-client#48]
If you attempt to sync a local repository of translation files to server, the client always quits with: "Exception: Not Found" error. This only happens when there is no resource on server already created, but according to the code in project.py, it should go through with next code, when HttpNotFound exception is raised.

```
def _get_stats_for_resource(self):
        """Get the statistics information for a resource."""
        try:
            r = self.do_url_request('resource_stats')
            logger.debug("Statistics response is %s" % r)
            stats = parse_json(r)
        except HttpNotFound:
            logger.debug("Resource not found, creating now... ")
            stats = {}
        except ssl.SSLError:
            logger.error("Invalid SSL certificate")
            raise
        except Exception, e:
            logger.debug(unicode(e))
            raise
        return stats
```

However the call always gets thrown into the Exception block, meaning the program never gets past the first source file. Either raise should be removed or HttpNotFound exception should be modified to respond correctly to the server Not Found reply.

**Comment by diegobz** [comment]
Fixed on master. The is a 0.11.x release coming soon.
