### ISSUE TITLE
Unable to use behind http proxy since 0.8

### ISSUE THREAD

**Issue by eMerzh** [transifex/transifex-client#49]
I was using the version 0.8 client, 

and i keep receiving the mail about my outdated version of the client, 
so i decided to upgrade to the 0.10. 

But then i was unable to pass my http proxy at work.

i have my env set as :
export http_proxy="192......:3128"
export https_proxy="192......:3128"

but it does not change anything...
i get stuck after the "pushing translations for ...."

**Comment by amanatidis** [comment]
@eMerzh, @petzlux  

We pushed a new branch:

https://github.com/transifex/transifex-client/tree/fix-proxies

Can you provide feedback if the problem still persists?

**Comment by petzlux** [comment]
@amanatidis 

Thanks I tried this, and had to add a proxy-header to the proxymanager config to make it work with our proxy (which doesnt let https traffic through without a user-agent header ):

https://github.com/petzlux/transifex-client/commit/c7410928afe198ed83bb2c94b2cbc1d5a170c967

Maybe something worth to include in your update ! 

Thanks for the update anyway

**Comment by amanatidis** [comment]
Thanks for the reply. Since a user agent header is needed we'll include a default one identifying the tx client.

**Comment by petzlux** [comment]
Your latest branch https://github.com/transifex/transifex-client/tree/fix-proxies works great  ! Cheers and waiting for merge into master

**Comment by bartlibert** [comment]
Any news on when this will get merged into the main branch?

**Comment by petzlux** [comment]
@amanatidis sorry to have to keep pestering for a chance to have this merged into master ?

**Comment by gnumdk** [comment]
Same here, can't pull behind a proxy... :(

**Comment by kouk** [comment]
@bartlibert @petzlux @gnumdk sorry for the delay. Unfortunately @amanatidis is not working on this project anymore, however I will try and get this done myself by the end of the week.

**Comment by teleivo** [comment]
any update :smiley:? I am also caged behind a proxy :disappointed:

**Comment by kouk** [comment]
@bartlibert @petzlux @gnumdk @teleivo fyi we are very close to merging #130 which will fix this problem.

**Comment by kouk** [comment]
#130 is merged to master, and will be in the upcoming release (next week). Would be grateful if you could test this and see if it suits you.

**Comment by kouk** [comment]
the new release is out, so I'm closing this issue now.
