### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by ericholscher** [transifex/transifex-client#51]
There is a bug that I was hitting in the released version on pypi that is fixed in master on GitHub. You should make a new release that has this bug fix in it. Currently it is breaking the installation instructions for Sphinx (http://sphinx-doc.org/latest/intl.html#using-transifex-service-for-team-translation) -- The bug is that it is getting a 404 when trying to create new resources.

It seems like every new project will hit this bug, and a new release should be made.

**Comment by bittner** [comment]
@diegobz What is holding you back with releasing a non-beta version?

You could finally close a whole bunch of GitHub issues. Is the command line client not generating any value for you guys? You should fix that. It's damaging your reputation, don't you care? And it's not a bit deal to package a release, technology-wise. Seriously!

**Comment by diegobz** [comment]
@bittner We had some problem with the windows version of it last time I checked. I will check the status of it again and prioritize it accordingly. Thanks for the bump!

**Comment by shimizukawa** [comment]
Is the problem related to #69 ?

**Comment by diegobz** [comment]
@shimizukawa It may be. To be honest I currently don't have the full picture of what the problem was/is. We are trying to reallocate resources from our team to be able move forward with it.

**Comment by diegobz** [comment]
The 0.11 is out.
