### ISSUE TITLE
Exception: Not found

### ISSUE THREAD

**Issue by vgezer** [transifex/transifex-client#62]
I have in my config file some sources like this:

```
[main]
host = https://www.transifex.com
type = PO

[xxx.issues]
file_filter = locale/<lang>/LC_MESSAGES/issues.po
source_file = locale/pot/issues.pot
source_lang = en
```

However when I executer `tx push -s` I only get this exception, but no useful information. The pot file exists in the `current_dir/locale/issues.pot`

How can I debug more?

**Comment by surkova** [comment]
Switching from 0.10 to beta helped me too

**Comment by julianlam** [comment]
Confirming that switching to a beta version helped. There was no `dev` version as of posting, so I ran

`sudo pip install transifex-client==0.11.1.beta`

**Comment by quinncomendant** [comment]
A year later, the stable version of transifex-client still fails with this error. The 0.11.1b0 works for me, but I would expect your product lifecycle to roll-out bug fixes faster than that. I'm non-plussed.

**Comment by bittner** [comment]
Duplicate of #51.
