### ISSUE TITLE
pull apple string error

### ISSUE THREAD

**Issue by hanchao** [transifex/transifex-client#64]
I install from source

```
user% git clone http://code.transifex.com/transifex-client
user% cd transifex-client
root# python setup.py install
```

Then try pull 

```
chaotekiMacBook-Pro:GPSLogger chaohan$ tx init
tx: There is already a tx folder!
Do you want to delete it and reinit the project? [y/N]: y
Creating .tx folder...
Transifex instance [https://www.transifex.com]: 
Creating skeleton...
Creating config file...
Done.
chaotekiMacBook-Pro:GPSLogger chaohan$ tx set --auto-remote https://www.transifex.com/projects/p/chatsecure
Auto configuring local project from remote URL...
Getting details for project chatsecure
2 resources found. Configuring...
Configuring resource chatsecure.appstorestrings.
Configuring resource chatsecure.strings.
chaotekiMacBook-Pro:GPSLogger chaohan$ tx pull -a
New translations found for the following languages: el, bo, da_DK, vi, ca, it, nl_NL, ar, cs, id, es, ro_RO, ru, no, tr, sl_SI, pt_PT, pl, fr, hy, pt_BR, uz@Cyrl, zh_TW, hu, he, fa_IR, uz, zh_CN, sv, sk, de, sl
Pulling new translations for resource chatsecure.appstorestrings (source: None)
 -> el: translations/chatsecure.appstorestrings/el.strings
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by amanatidis** [comment]
Hi @akissa,

Sorry for the late response. Can you check against the following branch:

https://github.com/transifex/transifex-client/tree/handle-charset

**Comment by akissa** [comment]
That works partially, still getting the error on one file. Will investigate further.

**Comment by amanatidis** [comment]
I can also look into it if you give me project, resource info

**Comment by akissa** [comment]
The project is mailscanner and resource info baruwa.languages, the my - etc/reports/my/languages.conf.strings is the one generating the error

**Comment by amanatidis** [comment]
Strange since I tried (project:mailscanner, resource:languages.conf) and (project:baruwa, resource:languages) with tx pull -a and it works.

**Comment by akissa** [comment]
Weird i still get

$ tx pull -r baruwa.languages -a -f
New translations found for the following languages: my, pt_BR, vi_VN
Pulling translations for resource baruwa.languages (source: etc/reports/en/languages.conf.strings)
 -> el: etc/reports/el/languages.conf.strings
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte
