### ISSUE TITLE
push string 

### ISSUE THREAD

**Issue by hanchao** [transifex/transifex-client#68]
I pull string from transifex
`tx pull`
Edit in local,then push to transifex. 
`tx push -t`
All strings  is Translated, why?

My project: https://www.transifex.com/projects/p/mapediter/

**Comment by diegobz** [comment]
This depends on the file format used by project. In your case, I think the .strings files had a the behavior of having English content filled in for missing translations, so when you pushed it back, the source content would be used as translations.

This has changed now. To workaround that, now .strings files have the untranslated entries in the downloaded file commented out, so if you push the file back the commented out entries (with source content content) are not taken into account.
