### ISSUE TITLE
Wrong <lang> when resource is region specific

### ISSUE THREAD

**Issue by maclir** [transifex/transifex-client#73]
It would be nice if transifex api would provide the correct region name in `<lang>` placeholder for android.

```
[android.strings]
source_lang = en
source_file = src/main/res/values/strings.xml
file_filter = src/main/res/values-<lang>/strings.xml
type = ANDROID
```

according to: http://developer.android.com/guide/topics/resources/providing-resources.html#AlternativeResources

The proper path for string resources would be: `values-[locale]-r[region]`
Which makes it reasonable for `<lang>` to be replaced by `[locale]-r[region]`. But this is not the case and it actually is: `[locale]_[region]` which is useless for android.

**Comment by canton7** [comment]
I'm love to see this as well. .NET wants to see lang-region, but it appears there's no way to appease it without manually mapping each language individually.

**Comment by diegobz** [comment]
This can be achieved by using language mapping: https://docs.transifex.com/client/client-configuration#language-mappings

**Comment by barbeau** [comment]
So, to save someone a stop looking this up in the above link, for Android this looks like:

~~~
[main]
host = https://www.transifex.com
lang_map = de-DE: de-rDE, zh-Hans: zh-rCN
~~~
