### ISSUE TITLE
Underscore vs. hyphen in locale code

### ISSUE THREAD

**Issue by Ede123** [transifex/transifex-client#76]
By default underscores are used in locale codes, e.g "en_US"

For some applications hyphens might be preferred though, e.g. Firefox uses BCP 47 language codes that look like "en-US".

Therefore if you try to push or pull translations you'll inevitably end up with conflicts, e.g.
* American English translations ending up in a "en_US" folder when you'd expect an "en-US" folder.
* `pull -l en-US` failing (or rather succeding but doing nothing) because of the hyphen
* `push -t -l en_US` failing when your traslation is actually located in "en-US"

A possibility to define whether to use underscores or hyphens would be necessary (e.g. as command line option and/or config setting.
Otherwise an automatic detection would be required.

Note that the same considerations also apply regarding the case of the country code (e.g. "en_us" vs "en_US")

**Comment by diegobz** [comment]
@Ede123 you can specify language mapping in the config file. Take a look at http://docs.transifex.com/developer/client/config#language-map

**Comment by Ede123** [comment]
@diegobz I saw this possibility, but I'd have to add a mapping for every language I use, right?

So either I would have to add mappings as I add new languages, or set all possible maps from the start. Both not really nice solutions I suppose...

**Comment by olliechick** [comment]
> @Ede123 you can specify language mapping in the config file. Take a look at http://docs.transifex.com/developer/client/config#language-map

This is now a dead link; this seems to be where this information is now: https://developers.transifex.com/docs/using-the-client#language-management
