### ISSUE TITLE
0.11b3 crashes on Windows 7 64bit

### ISSUE THREAD

**Issue by sledgehammer999** [transifex/transifex-client#82]
I was happily using 0.10 until I wanted to push a new resource. It refused. After checking the online docs I saw a note telling that I should use 0.11b3 otherwise the push will fail.
So I downloaded 0.11b3 from the site link. But now no matter what I do, even a simple `tx --version` or `tx --help` results in the following traceback:

```
Traceback (most recent call last):
  File "tx", line 9, in <module>
  File "zipextimporter.pyc", line 82, in load_module
  File "txclib\utils.pyc", line 3, in <module>
  File "zipextimporter.pyc", line 82, in load_module
  File "ssl.pyc", line 97, in <module>
  File "zipextimporter.pyc", line 98, in load_module
ImportError: MemoryLoadLibrary failed loading _ssl.pyd
```

Please can you fix it? Thank you.

**Comment by Underground78** [comment]
I can confirm this issue.

**Comment by sledgehammer999** [comment]
Any news on this?

**Comment by diegobz** [comment]
@sledgehammer999 we are going to check this out.

**Comment by sledgehammer999** [comment]
Just so you know, even under a clean Windows 7 64bit VM it still crashes with the same traceback.

**Comment by amanatidis** [comment]
@sledgehammer999 Can you redownload from [here](http://docs.transifex.com/client/setup) and report if it works? Thank you

**Comment by Underground78** [comment]
I'm not @sledgehammer999 but I can tell you that it still does not work. The file timestamp is still `04-May-2015 12:18` though.

**Comment by sledgehammer999** [comment]
Yes, it doesn't work. Same traceback.

**Comment by amanatidis** [comment]
Thanks @sledgehammer999, @Underground78 for the immediate response. We are investigating it and probably by tomorrow we'll provide a working executable.

**Comment by amanatidis** [comment]
@sledgehammer999, @Underground78 We uploaded a new version that seems to fix the problem. Can you verify?

**Comment by sledgehammer999** [comment]
Both `tx --help` and `tx --version` now work. I didn't test the rest of the funtions. I am closing this and I encounter problems I am going to report back.
Thank you for fixing it.

**Comment by Underground78** [comment]
I can confirm it works fine at least to pull translations. Thanks!

**Comment by phihag** [comment]
Can you elaborate on what you changed to fix this error? I'm seeing the same in an unrelated application.
