### ISSUE TITLE
Dont store password in plain text.

### ISSUE THREAD

**Issue by ushis** [transifex/transifex-client#9]
I was really surprised to find my plain text password in my .transifexrc. Please use an API Key or something. This Article [0] covers a nice solution, which is not hard to implement on the server and the client.

[0] http://www.thebuzzmedia.com/designing-a-secure-rest-api-without-oauth-authentication/

**Comment by marciomazza** [comment]
Well... Forgive me to intrude into your workflow, but I suggest this issue is relabelled as `bug` instead of an `enhancement` (as I see it is labelled now). Storing passwords in plain text cannot be considered a feature but rather a security breach.

And please... give this higher priority.

**Comment by diegobz** [comment]
We are currently creating the spec of the new API and it will support tokens. We don't have a time frame for that to be released yet, but we are actively working on it. Once we have that infra in the server side, implementing it in the CLI will be a piece of cake.

**Comment by shivapoudel** [comment]
@diegobz you mean new API will support tokens. Also one confusion for me will that API will be open for `https://www.transifex.com/api/2/project/axiscomposer/languages/` link so we can easily fetch translators and and add thanks note.

**Comment by quinncomendant** [comment]
I agree with the others who said this is a serious security issue. Thanks for prioritizing.

**Comment by samuelchan22** [comment]
We've added support for API tokens for our API, and it'll also work in the client:
https://docs.transifex.com/api/introduction#authentication

**Comment by kouk** [comment]
Related to this: https://github.com/transifex/transifex-client/pull/224
