### ISSUE TITLE
Pull in reviewed mode returns empty strings for resx files

### ISSUE THREAD

**Issue by roman-yagodin** [transifex/transifex-client#92]
According to the [docs](http://docs.transifex.com/formats/):

>  Currently, the available modes when using the Client or the API, are:
> -  reviewed, for files having only reviewed translations.
> -  translator, for files that are suitable for off-line translation of the resource.
> -  developer, for files that are suitable to be used by developers in their source code tree.
> 
> However, some file formats require to have the untranslated entries filled in with the source strings so using one of the modes mentioned above you'll get a file that won't have the untranslated strings empty. For that case we also provide two modes that "bypass" this rule for the sake of conveniece. These modes are available when using the API.
> -  onlytranslated the response will include the translated strings and the untranslated ones will be returned empty.
> -  onlyreviewed, the response will include the reviewed strings and the rest (translated or not) will be returned empty.

So, as far as I can understand, `tx pull --mode=reviewed` should return only reviewed strings, but no others:

``` XML
...
<data name="//Host//HostSettings.String" xml:space="preserve">
    <value>Настройки хоста</value>
  </data>
...
```

But instead it returns empty strings for untranslated (and unreviewed):

``` XML
...
<data name="//Host//HostSettings.String" xml:space="preserve">
    <value>Настройки хоста</value>
  </data>
<data name="//Host//SiteManagement.String" xml:space="preserve">
    <value></value>
</data>
...
```

It looks like it works in _onlyreviewed_ mode (which, as docs state, available only via API).

This broke localization in case of some .NET apps (like DNN Platform), as app cannot fallback to a string in the default resource file if there is an empty string in the translation file.

**Comment by roman-yagodin** [comment]
Currently I need to apply some kind of post-processing of every resx file after pull, i.e. with XSL transform script like this: [remove-empty-entries.xslt](https://github.com/roman-yagodin/R7.DnnLocalization/blob/master/xslt/remove-empty-entries.xslt)

**Comment by diegobz** [comment]
This is an issue on the file format export from Transifex, rather then the CLI tool. If it still persists, please sent an email to support at transifex.com.
