### ISSUE TITLE
Transifex Client is not compatible with Python 3.

### ISSUE THREAD

**Issue by kerkeslager** [transifex/transifex-client#93]
When calling `pip install transifex-client` with Python 3.4.0, I get the following error:

`TypeError: startswith first arg must be str or a tuple of str, not bytes`

This is probably an issue with not supporting Python 3.

I installed separately from my virtual environment using `apt-get`, but this is less than ideal. As more people switch to Python 3, this will become a larger problem.

**Comment by diegobz** [comment]
Hey @kerkeslager, can you try `pip install transifex-client==0.11b3` and let us know?

**Comment by kerkeslager** [comment]
@diegobz That installs correctly. I'll use it to pull in some translations this afternoon (once they're done) and let you know how it goes.

**Comment by kerkeslager** [comment]
Thanks for the quick turnaround. :simple_smile:

**Comment by kerkeslager** [comment]
@diegobz I ran a full cycle of `tx pull`, `./manage.py makemessages --all`, and `tx push` using Transifex client 0.11b3 and Python 3.4.0, and did sanity checks against the data at each step. Everything seems good. :+1: from me, thanks for your time and work.

**Comment by diegobz** [comment]
@kerkeslager Nice. We'll prioritize a final version of the client soon then. Thanks.

**Comment by bittner** [comment]
Related to #51.

Would be good if you could do a **test matrix** for all supported Python versions, e.g. using [tox](http://tox.readthedocs.org/en/latest/) and/or the features of Travis-CI. See the [django-analytical project](https://github.com/jcassee/django-analytical/blob/master/.travis.yml) for an easy (yet complex) example.

**Comment by barry1955** [comment]
Hi, I have just tried the above `tx pull, ./manage.py makemessages --all`"

I get the following error now:  

`(gnode) C:\usr\share\geonode\geonode>pip install transifex-client==0.11b3
Collecting transifex-client==0.11b3
  Using cached transifex-client-0.11b3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\barry\AppData\Local\Temp\pip-build-7c87nr6a\transifex-client\setup.py", line 24, in <module>
        from py2exe.build_exe import py2exe as build_exe
    ImportError: cannot import name 'py2exe'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\barry\AppData\Local\Temp\pip-build-7c87nr6a\transifex-client\`

I have installed py2exe.  

Any ideas would be great.

I'm on Windoze 10 64 bit, Python 3.5.1 

Any help would be ideas would be greatly appreciated, thanks.

Stay well.
