### ISSUE TITLE
type = PHP_ARRAY outputs files with syntax errors

### ISSUE THREAD

**Issue by mrclay** [transifex/transifex-client#96]
Expected: No matter what the translator enters in Transifex, the resulting output should be a valid string in PHP ([spec](https://github.com/php/php-langspec/blob/master/spec/19-grammar.md#string-literals), [manual](http://php.net/manual/en/language.types.string.php#language.types.string.syntax)).

Actual: `tx pull` output an invalid string ([line 6](https://github.com/Elgg/Elgg/blob/1.12/mod/embed/languages/it.php#L6)) in one of the files.

Note that the [source file](https://github.com/Elgg/Elgg/blob/1.12/mod/embed/languages/en.php#L6) uses single-quoted strings; perhaps the client expects all strings to be double-quoted? If so, the [documentation](http://docs.transifex.com/formats/php/) should specify that.

I don't know exactly what character(s) were entered into Transifex that caused the problem, as someone else fixed it. I suspect it was `\`.

**Comment by mrclay** [comment]
Would using only double-quoted strings help, as shown in your [sample data](http://docs.transifex.com/formats/php/#sample-data)?

**Comment by dimoschi** [comment]
@mrclay Backslash '\' is used as escape character in PHP, so if you want a backslash to appear in your translation you have to escape backslash with another one. So in this case, the right way is:
`'embed:upload' => 'Carica media\\'`

**Comment by mrclay** [comment]
The invalid string was output by Transifex client, not by developers/translators. That's why I'm reporting it as a bug :)

**Comment by mrclay** [comment]
I clarified the issue description a bit.

**Comment by dimoschi** [comment]
@mrclay Can you please point me to the Project in Transifex? It will help us better understand the issue.
Also if possible use support@transifex.com for any issues or questions regarding Transifex and Transifex Client & API.

**Comment by mrclay** [comment]
Project: https://www.transifex.com/elgg/elgg-core/
Problem string was 4 in the embed resource: https://www.transifex.com/elgg/elgg-core/viewstrings/#it/embed/15698271 (but it's been changed since)

**Comment by mrclay** [comment]
Would you prefer I close this and go through the email support system, or just do that with future issues?

**Comment by juho-jaakkola** [comment]
> I don't know exactly what character(s) were entered into Transifex that caused the problem, as someone else fixed it. I suspect it was \\.

I was the one who fixed the string in Transifex. The translation was identical to the one pulled in using the client: ```Carica media\```.

So this is definitely a bug in Transifex. It allows you to enter any characters but it doesn't escape them.

**Comment by dimoschi** [comment]
@juho-jaakkola Thanks for verifying this!
@mrclay I recommended this for future use, as it helps us track your reports and request easier.

I have reported this to our Developers.

**Comment by diegobz** [comment]
I'm closing this as this looks related to the file outputted exported from Transifex, rather than something related to the CLI itself.
