### ISSUE TITLE
Support Python versions 3.4 and 3.5

### ISSUE THREAD

**Issue by bittner** [transifex/transifex-client#97]
All recent Python 3 versions should be supported better sooner than later.

## Background

The Python eco-system, and Unix-style operating system specifically, are now ready to move away from Python 2, finally, and make Python 3 the new default. This is expected to happen, for example, in Debian / Ubuntu in spring 2016.

Also, Python version 3.5 was released in September 2015, and is expected to be the default Python version on Ubuntu starting with the next LTS release (see [plans for version 16.04](https://wiki.ubuntu.com/Python)).

Hence, it is imperative to support Python versions 3.4 and 3.5. -- At the moment only 3.3 is supported along with Python 2.6 and 2.7 according to the [latest package on PyPI](https://pypi.python.org/pypi/transifex-client). However, Python 3.4 was already the default Python 3 version on Ubuntu 14.04, that's 1.5 years ago.

**Comment by bittner** [comment]
Related to issue #90.

**Comment by bittner** [comment]
Related to issue #51.

**Comment by dimoschi** [comment]
@bittner Thank you for your feedback. We will try to improve Transifex Client, since there is a great appeal from many of our customers.
Unfortunately I can't give an ETA, but we will work towards an improvement of the current beta version.

**Comment by EliotBerriot** [comment]
I agree, I've been bitten by this today, in a Python 3 project, and I have to install `transifex-client` in global Python 2 packages to be able to use it. And I have to constantly switch from one terminal to another, since I have to use two different versions of Python. 

Python 3 is becoming more and more important, and I hope it will be supported soon by Transifex !

**Comment by diegobz** [comment]
Python 3.5 is supported on master now. Related commits: f695608 and abf7d0f.

**Comment by bittner** [comment]
Thank you. It would be helpful, though, to ensure that also Python 3.4, and ideally Python 3.3, are supported. That should not be that much of additional effort.
